name: Bit verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Bit
        uses: bit-tasks/init@v3
        with:
            ws-dir: '.'

      - name: Bit Verify
        uses: bit-tasks/verify@v2